"""add_missing_resume_cols

Revision ID: 3313ec14f42b
Revises: 825bee241126
Create Date: 2026-04-02 15:28:57.864840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3313ec14f42b'
down_revision = '825bee241126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('extracted_text')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('email_sent_at')

    # ### end Alembic commands ###
