"""Add keywords field to Membership model

Revision ID: add_keywords_to_membership
Revises: 9276ecf7eb3c
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_keywords_to_membership'
down_revision = '9276ecf7eb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership', 'keywords')
    # ### end Alembic commands ###
