"""add meeting point locations multiselect

Revision ID: f06588656b31
Revises: 87a68521f99f
Create Date: 2025-12-07 14:35:51.859589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06588656b31'
down_revision = '87a68521f99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_point_locations',
    sa.Column('meeting_point_id', sa.Integer(), nullable=False),
    sa.Column('session_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_point_id'], ['meeting_location.id'], ),
    sa.ForeignKeyConstraint(['session_location_id'], ['session_location.id'], ),
    sa.PrimaryKeyConstraint('meeting_point_id', 'session_location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_point_locations')
    # ### end Alembic commands ###
